# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'projectNewChess.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import time,threading

class Ui_MainWindow(object):
    
    gameEnded = QtCore.pyqtSignal()
    whites_clock = None
    blacks_clock = None
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(601, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(800, 800))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMaximumSize(QtCore.QSize(600, 600))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMaximumSize(QtCore.QSize(600, 600))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setStyleSheet("color: rgb(255, 255, 255);")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setLineWidth(0)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page.sizePolicy().hasHeightForWidth())
        self.page.setSizePolicy(sizePolicy)
        self.page.setMaximumSize(QtCore.QSize(600, 550))
        self.page.setObjectName("page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setContentsMargins(0, -1, 0, 7)
        self.formLayout.setHorizontalSpacing(10)
        self.formLayout.setVerticalSpacing(4)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.w_mins = QtWidgets.QLineEdit(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_mins.sizePolicy().hasHeightForWidth())
        self.w_mins.setSizePolicy(sizePolicy)
        self.w_mins.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.w_mins.setFont(font)
        self.w_mins.setStyleSheet("color: rgb(0, 0, 0);")
        self.w_mins.setAlignment(QtCore.Qt.AlignCenter)
        self.w_mins.setClearButtonEnabled(False)
        self.w_mins.setObjectName("w_mins")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.w_mins)
        self.label_3 = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.w_secs = QtWidgets.QLineEdit(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_secs.sizePolicy().hasHeightForWidth())
        self.w_secs.setSizePolicy(sizePolicy)
        self.w_secs.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.w_secs.setFont(font)
        self.w_secs.setStyleSheet("color: rgb(0, 0, 0);")
        self.w_secs.setFrame(True)
        self.w_secs.setAlignment(QtCore.Qt.AlignCenter)
        self.w_secs.setObjectName("w_secs")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.w_secs)
        self.label_4 = QtWidgets.QLabel(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.label_4)
        self.label_10 = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.b_mins = QtWidgets.QLineEdit(self.page)
        self.b_mins.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.b_mins.setFont(font)
        self.b_mins.setStyleSheet("color: rgb(0, 0, 0);")
        self.b_mins.setAlignment(QtCore.Qt.AlignCenter)
        self.b_mins.setObjectName("b_mins")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.b_mins)
        self.label_1 = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_1.setFont(font)
        self.label_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_1.setObjectName("label_1")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_1)
        self.b_secs = QtWidgets.QLineEdit(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_secs.sizePolicy().hasHeightForWidth())
        self.b_secs.setSizePolicy(sizePolicy)
        self.b_secs.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.b_secs.setFont(font)
        self.b_secs.setStyleSheet("color: rgb(0, 0, 0);")
        self.b_secs.setAlignment(QtCore.Qt.AlignCenter)
        self.b_secs.setObjectName("b_secs")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.b_secs)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(7, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        self.label_11 = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.play = QtWidgets.QPushButton(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.play.sizePolicy().hasHeightForWidth())
        self.play.setSizePolicy(sizePolicy)
        self.play.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.play.setFont(font)
        self.play.setStyleSheet("color: rgb(0, 0, 0);")
        self.play.setAutoExclusive(False)
        self.play.setObjectName("play")
        self.horizontalLayout_2.addWidget(self.play)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 149, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_2.sizePolicy().hasHeightForWidth())
        self.page_2.setSizePolicy(sizePolicy)
        self.page_2.setObjectName("page_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMaximumSize(QtCore.QSize(600, 600))
        self.frame.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.b35 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b35.sizePolicy().hasHeightForWidth())
        self.b35.setSizePolicy(sizePolicy)
        self.b35.setMaximumSize(QtCore.QSize(72, 72))
        self.b35.setStyleSheet("background-color: rgb(20, 138, 0);")
        self.b35.setText("")
        self.b35.setAlignment(QtCore.Qt.AlignCenter)
        self.b35.setObjectName("b35")
        self.gridLayout_3.addWidget(self.b35, 9, 5, 1, 1)
        self.b47 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b47.sizePolicy().hasHeightForWidth())
        self.b47.setSizePolicy(sizePolicy)
        self.b47.setMaximumSize(QtCore.QSize(72, 72))
        self.b47.setStyleSheet("background-color:rgb(187, 255, 171);")
        self.b47.setText("")
        self.b47.setAlignment(QtCore.Qt.AlignCenter)
        self.b47.setObjectName("b47")
        self.gridLayout_3.addWidget(self.b47, 10, 11, 1, 1)
        self.b78 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b78.sizePolicy().hasHeightForWidth())
        self.b78.setSizePolicy(sizePolicy)
        self.b78.setMaximumSize(QtCore.QSize(72, 72))
        self.b78.setStyleSheet("background-color:rgb(187, 255, 171);")
        self.b78.setText("")
        self.b78.setAlignment(QtCore.Qt.AlignCenter)
        self.b78.setObjectName("b78")
        self.gridLayout_3.addWidget(self.b78, 13, 12, 1, 1)
        self.b14 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b14.sizePolicy().hasHeightForWidth())
        self.b14.setSizePolicy(sizePolicy)
        self.b14.setMaximumSize(QtCore.QSize(72, 72))
        self.b14.setStyleSheet("background-color:rgb(187, 255, 171);")
        self.b14.setText("")
        self.b14.setAlignment(QtCore.Qt.AlignCenter)
        self.b14.setObjectName("b14")
        self.gridLayout_3.addWidget(self.b14, 7, 3, 1, 1)
        self.b34 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b34.sizePolicy().hasHeightForWidth())
        self.b34.setSizePolicy(sizePolicy)
        self.b34.setMaximumSize(QtCore.QSize(72, 72))
        self.b34.setStyleSheet("background-color:rgb(187, 255, 171);")
        self.b34.setText("")
        self.b34.setAlignment(QtCore.Qt.AlignCenter)
        self.b34.setObjectName("b34")
        self.gridLayout_3.addWidget(self.b34, 9, 3, 1, 1)
        self.b28 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b28.sizePolicy().hasHeightForWidth())
        self.b28.setSizePolicy(sizePolicy)
        self.b28.setMaximumSize(QtCore.QSize(72, 72))
        self.b28.setStyleSheet("background-color: rgb(20, 138, 0);")
        self.b28.setText("")
        self.b28.setAlignment(QtCore.Qt.AlignCenter)
        self.b28.setObjectName("b28")
        self.gridLayout_3.addWidget(self.b28, 8, 12, 1, 1)
        self.b57 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b57.sizePolicy().hasHeightForWidth())
        self.b57.setSizePolicy(sizePolicy)
        self.b57.setMaximumSize(QtCore.QSize(72, 72))
        self.b57.setStyleSheet("background-color: rgb(20, 138, 0);")
        self.b57.setText("")
        self.b57.setAlignment(QtCore.Qt.AlignCenter)
        self.b57.setObjectName("b57")
        self.gridLayout_3.addWidget(self.b57, 11, 11, 1, 1)
        self.b21 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b21.sizePolicy().hasHeightForWidth())
        self.b21.setSizePolicy(sizePolicy)
        self.b21.setMaximumSize(QtCore.QSize(72, 72))
        self.b21.setStyleSheet("background-color:rgb(187, 255, 171);")
        self.b21.setText("")
        self.b21.setScaledContents(False)
        self.b21.setAlignment(QtCore.Qt.AlignCenter)
        self.b21.setObjectName("b21")
        self.gridLayout_3.addWidget(self.b21, 8, 0, 1, 1)
        self.b53 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b53.sizePolicy().hasHeightForWidth())
        self.b53.setSizePolicy(sizePolicy)
        self.b53.setMaximumSize(QtCore.QSize(72, 72))
        self.b53.setStyleSheet("background-color: rgb(20, 138, 0);")
        self.b53.setText("")
        self.b53.setAlignment(QtCore.Qt.AlignCenter)
        self.b53.setObjectName("b53")
        self.gridLayout_3.addWidget(self.b53, 11, 2, 1, 1)
        self.b38 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b38.sizePolicy().hasHeightForWidth())
        self.b38.setSizePolicy(sizePolicy)
        self.b38.setMaximumSize(QtCore.QSize(72, 72))
        self.b38.setStyleSheet("background-color:rgb(187, 255, 171);")
        self.b38.setText("")
        self.b38.setAlignment(QtCore.Qt.AlignCenter)
        self.b38.setObjectName("b38")
        self.gridLayout_3.addWidget(self.b38, 9, 12, 1, 1)
        self.b84 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b84.sizePolicy().hasHeightForWidth())
        self.b84.setSizePolicy(sizePolicy)
        self.b84.setMaximumSize(QtCore.QSize(72, 72))
        self.b84.setStyleSheet("background-color: rgb(20, 138, 0);")
        self.b84.setText("")
        self.b84.setAlignment(QtCore.Qt.AlignCenter)
        self.b84.setObjectName("b84")
        self.gridLayout_3.addWidget(self.b84, 14, 3, 1, 1)
        self.b17 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b17.sizePolicy().hasHeightForWidth())
        self.b17.setSizePolicy(sizePolicy)
        self.b17.setMaximumSize(QtCore.QSize(72, 72))
        self.b17.setStyleSheet("background-color: rgb(20, 138, 0);")
        self.b17.setText("")
        self.b17.setAlignment(QtCore.Qt.AlignCenter)
        self.b17.setObjectName("b17")
        self.gridLayout_3.addWidget(self.b17, 7, 11, 1, 1)
        self.b72 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b72.sizePolicy().hasHeightForWidth())
        self.b72.setSizePolicy(sizePolicy)
        self.b72.setMaximumSize(QtCore.QSize(72, 72))
        self.b72.setStyleSheet("background-color:rgb(187, 255, 171);")
        self.b72.setText("")
        self.b72.setAlignment(QtCore.Qt.AlignCenter)
        self.b72.setObjectName("b72")
        self.gridLayout_3.addWidget(self.b72, 13, 1, 1, 1)
        self.b18 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b18.sizePolicy().hasHeightForWidth())
        self.b18.setSizePolicy(sizePolicy)
        self.b18.setMaximumSize(QtCore.QSize(72, 72))
        self.b18.setStyleSheet("background-color:rgb(187, 255, 171);")
        self.b18.setText("")
        self.b18.setAlignment(QtCore.Qt.AlignCenter)
        self.b18.setObjectName("b18")
        self.gridLayout_3.addWidget(self.b18, 7, 12, 1, 1)
        self.b71 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b71.sizePolicy().hasHeightForWidth())
        self.b71.setSizePolicy(sizePolicy)
        self.b71.setMaximumSize(QtCore.QSize(72, 72))
        self.b71.setStyleSheet("background-color: rgb(20, 138, 0);")
        self.b71.setText("")
        self.b71.setAlignment(QtCore.Qt.AlignCenter)
        self.b71.setObjectName("b71")
        self.gridLayout_3.addWidget(self.b71, 13, 0, 1, 1)
        self.b55 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b55.sizePolicy().hasHeightForWidth())
        self.b55.setSizePolicy(sizePolicy)
        self.b55.setMaximumSize(QtCore.QSize(72, 72))
        self.b55.setStyleSheet("background-color: rgb(20, 138, 0);")
        self.b55.setText("")
        self.b55.setAlignment(QtCore.Qt.AlignCenter)
        self.b55.setObjectName("b55")
        self.gridLayout_3.addWidget(self.b55, 11, 5, 1, 1)
        self.b36 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b36.sizePolicy().hasHeightForWidth())
        self.b36.setSizePolicy(sizePolicy)
        self.b36.setMaximumSize(QtCore.QSize(72, 72))
        self.b36.setStyleSheet("background-color:rgb(187, 255, 171);")
        self.b36.setText("")
        self.b36.setAlignment(QtCore.Qt.AlignCenter)
        self.b36.setObjectName("b36")
        self.gridLayout_3.addWidget(self.b36, 9, 7, 1, 1)
        self.b66 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b66.sizePolicy().hasHeightForWidth())
        self.b66.setSizePolicy(sizePolicy)
        self.b66.setMaximumSize(QtCore.QSize(72, 72))
        self.b66.setStyleSheet("background-color: rgb(20, 138, 0);")
        self.b66.setText("")
        self.b66.setAlignment(QtCore.Qt.AlignCenter)
        self.b66.setObjectName("b66")
        self.gridLayout_3.addWidget(self.b66, 12, 7, 1, 1)
        self.b56 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b56.sizePolicy().hasHeightForWidth())
        self.b56.setSizePolicy(sizePolicy)
        self.b56.setMaximumSize(QtCore.QSize(72, 72))
        self.b56.setStyleSheet("background-color:rgb(187, 255, 171);")
        self.b56.setText("")
        self.b56.setAlignment(QtCore.Qt.AlignCenter)
        self.b56.setObjectName("b56")
        self.gridLayout_3.addWidget(self.b56, 11, 7, 1, 1)
        self.b52 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b52.sizePolicy().hasHeightForWidth())
        self.b52.setSizePolicy(sizePolicy)
        self.b52.setMaximumSize(QtCore.QSize(72, 72))
        self.b52.setStyleSheet("background-color:rgb(187, 255, 171);")
        self.b52.setText("")
        self.b52.setAlignment(QtCore.Qt.AlignCenter)
        self.b52.setObjectName("b52")
        self.gridLayout_3.addWidget(self.b52, 11, 1, 1, 1)
        self.b51 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b51.sizePolicy().hasHeightForWidth())
        self.b51.setSizePolicy(sizePolicy)
        self.b51.setMaximumSize(QtCore.QSize(72, 72))
        self.b51.setStyleSheet("background-color: rgb(20, 138, 0);")
        self.b51.setText("")
        self.b51.setAlignment(QtCore.Qt.AlignCenter)
        self.b51.setObjectName("b51")
        self.gridLayout_3.addWidget(self.b51, 11, 0, 1, 1)
        self.b26 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b26.sizePolicy().hasHeightForWidth())
        self.b26.setSizePolicy(sizePolicy)
        self.b26.setMaximumSize(QtCore.QSize(72, 72))
        self.b26.setStyleSheet("background-color: rgb(20, 138, 0);")
        self.b26.setText("")
        self.b26.setAlignment(QtCore.Qt.AlignCenter)
        self.b26.setObjectName("b26")
        self.gridLayout_3.addWidget(self.b26, 8, 7, 1, 1)
        self.b48 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b48.sizePolicy().hasHeightForWidth())
        self.b48.setSizePolicy(sizePolicy)
        self.b48.setMaximumSize(QtCore.QSize(72, 72))
        self.b48.setStyleSheet("background-color: rgb(20, 138, 0);")
        self.b48.setText("")
        self.b48.setAlignment(QtCore.Qt.AlignCenter)
        self.b48.setObjectName("b48")
        self.gridLayout_3.addWidget(self.b48, 10, 12, 1, 1)
        self.b23 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b23.sizePolicy().hasHeightForWidth())
        self.b23.setSizePolicy(sizePolicy)
        self.b23.setMaximumSize(QtCore.QSize(72, 72))
        self.b23.setStyleSheet("background-color:rgb(187, 255, 171);")
        self.b23.setText("")
        self.b23.setScaledContents(False)
        self.b23.setAlignment(QtCore.Qt.AlignCenter)
        self.b23.setObjectName("b23")
        self.gridLayout_3.addWidget(self.b23, 8, 2, 1, 1)
        self.b13 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b13.sizePolicy().hasHeightForWidth())
        self.b13.setSizePolicy(sizePolicy)
        self.b13.setMaximumSize(QtCore.QSize(72, 72))
        self.b13.setStyleSheet("background-color: rgb(20, 138, 0);")
        self.b13.setText("")
        self.b13.setAlignment(QtCore.Qt.AlignCenter)
        self.b13.setObjectName("b13")
        self.gridLayout_3.addWidget(self.b13, 7, 2, 1, 1)
        self.b85 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b85.sizePolicy().hasHeightForWidth())
        self.b85.setSizePolicy(sizePolicy)
        self.b85.setMaximumSize(QtCore.QSize(72, 72))
        self.b85.setStyleSheet("background-color:rgb(187, 255, 171);")
        self.b85.setText("")
        self.b85.setAlignment(QtCore.Qt.AlignCenter)
        self.b85.setObjectName("b85")
        self.gridLayout_3.addWidget(self.b85, 14, 5, 1, 1)
        self.b76 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b76.sizePolicy().hasHeightForWidth())
        self.b76.setSizePolicy(sizePolicy)
        self.b76.setMaximumSize(QtCore.QSize(72, 72))
        self.b76.setStyleSheet("background-color:rgb(187, 255, 171);")
        self.b76.setText("")
        self.b76.setAlignment(QtCore.Qt.AlignCenter)
        self.b76.setObjectName("b76")
        self.gridLayout_3.addWidget(self.b76, 13, 7, 1, 1)
        self.b68 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b68.sizePolicy().hasHeightForWidth())
        self.b68.setSizePolicy(sizePolicy)
        self.b68.setMaximumSize(QtCore.QSize(72, 72))
        self.b68.setStyleSheet("background-color: rgb(20, 138, 0);")
        self.b68.setText("")
        self.b68.setAlignment(QtCore.Qt.AlignCenter)
        self.b68.setObjectName("b68")
        self.gridLayout_3.addWidget(self.b68, 12, 12, 1, 1)
        self.b27 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b27.sizePolicy().hasHeightForWidth())
        self.b27.setSizePolicy(sizePolicy)
        self.b27.setMaximumSize(QtCore.QSize(72, 72))
        self.b27.setStyleSheet("background-color:rgb(187, 255, 171);")
        self.b27.setText("")
        self.b27.setAlignment(QtCore.Qt.AlignCenter)
        self.b27.setObjectName("b27")
        self.gridLayout_3.addWidget(self.b27, 8, 11, 1, 1)
        self.b11 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b11.sizePolicy().hasHeightForWidth())
        self.b11.setSizePolicy(sizePolicy)
        self.b11.setMaximumSize(QtCore.QSize(72, 72))
        self.b11.setStyleSheet("background-color: rgb(20, 138, 0);")
        self.b11.setText("")
        self.b11.setAlignment(QtCore.Qt.AlignCenter)
        self.b11.setObjectName("b11")
        self.gridLayout_3.addWidget(self.b11, 7, 0, 1, 1)
        self.b81 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b81.sizePolicy().hasHeightForWidth())
        self.b81.setSizePolicy(sizePolicy)
        self.b81.setMaximumSize(QtCore.QSize(72, 72))
        self.b81.setStyleSheet("background-color:rgb(187, 255, 171);")
        self.b81.setText("")
        self.b81.setAlignment(QtCore.Qt.AlignCenter)
        self.b81.setObjectName("b81")
        self.gridLayout_3.addWidget(self.b81, 14, 0, 1, 1)
        self.b77 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b77.sizePolicy().hasHeightForWidth())
        self.b77.setSizePolicy(sizePolicy)
        self.b77.setMaximumSize(QtCore.QSize(72, 72))
        self.b77.setStyleSheet("background-color: rgb(20, 138, 0);")
        self.b77.setText("")
        self.b77.setAlignment(QtCore.Qt.AlignCenter)
        self.b77.setObjectName("b77")
        self.gridLayout_3.addWidget(self.b77, 13, 11, 1, 1)
        self.b83 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b83.sizePolicy().hasHeightForWidth())
        self.b83.setSizePolicy(sizePolicy)
        self.b83.setMaximumSize(QtCore.QSize(72, 72))
        self.b83.setStyleSheet("background-color:rgb(187, 255, 171);")
        self.b83.setText("")
        self.b83.setAlignment(QtCore.Qt.AlignCenter)
        self.b83.setObjectName("b83")
        self.gridLayout_3.addWidget(self.b83, 14, 2, 1, 1)
        self.b32 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b32.sizePolicy().hasHeightForWidth())
        self.b32.setSizePolicy(sizePolicy)
        self.b32.setMaximumSize(QtCore.QSize(72, 72))
        self.b32.setStyleSheet("background-color:rgb(187, 255, 171);")
        self.b32.setText("")
        self.b32.setAlignment(QtCore.Qt.AlignCenter)
        self.b32.setObjectName("b32")
        self.gridLayout_3.addWidget(self.b32, 9, 1, 1, 1)
        self.b54 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b54.sizePolicy().hasHeightForWidth())
        self.b54.setSizePolicy(sizePolicy)
        self.b54.setMaximumSize(QtCore.QSize(72, 72))
        self.b54.setStyleSheet("background-color:rgb(187, 255, 171);")
        self.b54.setText("")
        self.b54.setAlignment(QtCore.Qt.AlignCenter)
        self.b54.setObjectName("b54")
        self.gridLayout_3.addWidget(self.b54, 11, 3, 1, 1)
        self.b41 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b41.sizePolicy().hasHeightForWidth())
        self.b41.setSizePolicy(sizePolicy)
        self.b41.setMaximumSize(QtCore.QSize(72, 72))
        self.b41.setStyleSheet("background-color:rgb(187, 255, 171);")
        self.b41.setText("")
        self.b41.setAlignment(QtCore.Qt.AlignCenter)
        self.b41.setObjectName("b41")
        self.gridLayout_3.addWidget(self.b41, 10, 0, 1, 1)
        self.b61 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b61.sizePolicy().hasHeightForWidth())
        self.b61.setSizePolicy(sizePolicy)
        self.b61.setMaximumSize(QtCore.QSize(72, 72))
        self.b61.setStyleSheet("background-color:rgb(187, 255, 171);")
        self.b61.setText("")
        self.b61.setAlignment(QtCore.Qt.AlignCenter)
        self.b61.setObjectName("b61")
        self.gridLayout_3.addWidget(self.b61, 12, 0, 1, 1)
        self.b22 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b22.sizePolicy().hasHeightForWidth())
        self.b22.setSizePolicy(sizePolicy)
        self.b22.setMaximumSize(QtCore.QSize(72, 72))
        self.b22.setStyleSheet("background-color: rgb(20, 138, 0);")
        self.b22.setText("")
        self.b22.setScaledContents(False)
        self.b22.setAlignment(QtCore.Qt.AlignCenter)
        self.b22.setObjectName("b22")
        self.gridLayout_3.addWidget(self.b22, 8, 1, 1, 1)
        self.b24 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b24.sizePolicy().hasHeightForWidth())
        self.b24.setSizePolicy(sizePolicy)
        self.b24.setMaximumSize(QtCore.QSize(72, 72))
        self.b24.setStyleSheet("background-color: rgb(20, 138, 0);")
        self.b24.setText("")
        self.b24.setAlignment(QtCore.Qt.AlignCenter)
        self.b24.setObjectName("b24")
        self.gridLayout_3.addWidget(self.b24, 8, 3, 1, 1)
        self.b16 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b16.sizePolicy().hasHeightForWidth())
        self.b16.setSizePolicy(sizePolicy)
        self.b16.setMaximumSize(QtCore.QSize(72, 72))
        self.b16.setStyleSheet("background-color:rgb(187, 255, 171);")
        self.b16.setText("")
        self.b16.setAlignment(QtCore.Qt.AlignCenter)
        self.b16.setObjectName("b16")
        self.gridLayout_3.addWidget(self.b16, 7, 7, 1, 1)
        self.b88 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b88.sizePolicy().hasHeightForWidth())
        self.b88.setSizePolicy(sizePolicy)
        self.b88.setMaximumSize(QtCore.QSize(72, 72))
        self.b88.setStyleSheet("background-color: rgb(20, 138, 0);")
        self.b88.setText("")
        self.b88.setAlignment(QtCore.Qt.AlignCenter)
        self.b88.setObjectName("b88")
        self.gridLayout_3.addWidget(self.b88, 14, 12, 1, 1)
        self.b44 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b44.sizePolicy().hasHeightForWidth())
        self.b44.setSizePolicy(sizePolicy)
        self.b44.setMaximumSize(QtCore.QSize(72, 72))
        self.b44.setStyleSheet("background-color: rgb(20, 138, 0);")
        self.b44.setText("")
        self.b44.setAlignment(QtCore.Qt.AlignCenter)
        self.b44.setObjectName("b44")
        self.gridLayout_3.addWidget(self.b44, 10, 3, 1, 1)
        self.b87 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b87.sizePolicy().hasHeightForWidth())
        self.b87.setSizePolicy(sizePolicy)
        self.b87.setMaximumSize(QtCore.QSize(72, 72))
        self.b87.setStyleSheet("background-color:rgb(187, 255, 171);")
        self.b87.setText("")
        self.b87.setAlignment(QtCore.Qt.AlignCenter)
        self.b87.setObjectName("b87")
        self.gridLayout_3.addWidget(self.b87, 14, 11, 1, 1)
        self.b65 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b65.sizePolicy().hasHeightForWidth())
        self.b65.setSizePolicy(sizePolicy)
        self.b65.setMaximumSize(QtCore.QSize(72, 72))
        self.b65.setStyleSheet("background-color:rgb(187, 255, 171);")
        self.b65.setText("")
        self.b65.setAlignment(QtCore.Qt.AlignCenter)
        self.b65.setObjectName("b65")
        self.gridLayout_3.addWidget(self.b65, 12, 5, 1, 1)
        self.b63 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b63.sizePolicy().hasHeightForWidth())
        self.b63.setSizePolicy(sizePolicy)
        self.b63.setMaximumSize(QtCore.QSize(72, 72))
        self.b63.setStyleSheet("background-color:rgb(187, 255, 171);")
        self.b63.setText("")
        self.b63.setAlignment(QtCore.Qt.AlignCenter)
        self.b63.setObjectName("b63")
        self.gridLayout_3.addWidget(self.b63, 12, 2, 1, 1)
        self.b75 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b75.sizePolicy().hasHeightForWidth())
        self.b75.setSizePolicy(sizePolicy)
        self.b75.setMaximumSize(QtCore.QSize(72, 72))
        self.b75.setStyleSheet("background-color: rgb(20, 138, 0);")
        self.b75.setText("")
        self.b75.setAlignment(QtCore.Qt.AlignCenter)
        self.b75.setObjectName("b75")
        self.gridLayout_3.addWidget(self.b75, 13, 5, 1, 1)
        self.b67 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b67.sizePolicy().hasHeightForWidth())
        self.b67.setSizePolicy(sizePolicy)
        self.b67.setMaximumSize(QtCore.QSize(72, 72))
        self.b67.setStyleSheet("background-color:rgb(187, 255, 171);")
        self.b67.setText("")
        self.b67.setAlignment(QtCore.Qt.AlignCenter)
        self.b67.setObjectName("b67")
        self.gridLayout_3.addWidget(self.b67, 12, 11, 1, 1)
        self.b33 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b33.sizePolicy().hasHeightForWidth())
        self.b33.setSizePolicy(sizePolicy)
        self.b33.setMaximumSize(QtCore.QSize(72, 72))
        self.b33.setStyleSheet("background-color: rgb(20, 138, 0);")
        self.b33.setText("")
        self.b33.setAlignment(QtCore.Qt.AlignCenter)
        self.b33.setObjectName("b33")
        self.gridLayout_3.addWidget(self.b33, 9, 2, 1, 1)
        self.b37 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b37.sizePolicy().hasHeightForWidth())
        self.b37.setSizePolicy(sizePolicy)
        self.b37.setMaximumSize(QtCore.QSize(72, 72))
        self.b37.setStyleSheet("background-color: rgb(20, 138, 0);")
        self.b37.setText("")
        self.b37.setAlignment(QtCore.Qt.AlignCenter)
        self.b37.setObjectName("b37")
        self.gridLayout_3.addWidget(self.b37, 9, 11, 1, 1)
        self.b46 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b46.sizePolicy().hasHeightForWidth())
        self.b46.setSizePolicy(sizePolicy)
        self.b46.setMaximumSize(QtCore.QSize(72, 72))
        self.b46.setStyleSheet("background-color: rgb(20, 138, 0);")
        self.b46.setText("")
        self.b46.setAlignment(QtCore.Qt.AlignCenter)
        self.b46.setObjectName("b46")
        self.gridLayout_3.addWidget(self.b46, 10, 7, 1, 1)
        self.b64 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b64.sizePolicy().hasHeightForWidth())
        self.b64.setSizePolicy(sizePolicy)
        self.b64.setMaximumSize(QtCore.QSize(72, 72))
        self.b64.setStyleSheet("background-color: rgb(20, 138, 0);")
        self.b64.setText("")
        self.b64.setAlignment(QtCore.Qt.AlignCenter)
        self.b64.setObjectName("b64")
        self.gridLayout_3.addWidget(self.b64, 12, 3, 1, 1)
        self.b12 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b12.sizePolicy().hasHeightForWidth())
        self.b12.setSizePolicy(sizePolicy)
        self.b12.setMaximumSize(QtCore.QSize(72, 72))
        self.b12.setStyleSheet("background-color:rgb(187, 255, 171);")
        self.b12.setText("")
        self.b12.setAlignment(QtCore.Qt.AlignCenter)
        self.b12.setObjectName("b12")
        self.gridLayout_3.addWidget(self.b12, 7, 1, 1, 1)
        self.b43 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b43.sizePolicy().hasHeightForWidth())
        self.b43.setSizePolicy(sizePolicy)
        self.b43.setMaximumSize(QtCore.QSize(72, 72))
        self.b43.setStyleSheet("background-color:rgb(187, 255, 171);")
        self.b43.setText("")
        self.b43.setAlignment(QtCore.Qt.AlignCenter)
        self.b43.setObjectName("b43")
        self.gridLayout_3.addWidget(self.b43, 10, 2, 1, 1)
        self.b86 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b86.sizePolicy().hasHeightForWidth())
        self.b86.setSizePolicy(sizePolicy)
        self.b86.setMaximumSize(QtCore.QSize(72, 72))
        self.b86.setStyleSheet("background-color: rgb(20, 138, 0);")
        self.b86.setText("")
        self.b86.setAlignment(QtCore.Qt.AlignCenter)
        self.b86.setObjectName("b86")
        self.gridLayout_3.addWidget(self.b86, 14, 7, 1, 1)
        self.b62 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b62.sizePolicy().hasHeightForWidth())
        self.b62.setSizePolicy(sizePolicy)
        self.b62.setMaximumSize(QtCore.QSize(72, 72))
        self.b62.setStyleSheet("background-color: rgb(20, 138, 0);")
        self.b62.setText("")
        self.b62.setAlignment(QtCore.Qt.AlignCenter)
        self.b62.setObjectName("b62")
        self.gridLayout_3.addWidget(self.b62, 12, 1, 1, 1)
        self.b42 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b42.sizePolicy().hasHeightForWidth())
        self.b42.setSizePolicy(sizePolicy)
        self.b42.setMaximumSize(QtCore.QSize(72, 72))
        self.b42.setStyleSheet("background-color: rgb(20, 138, 0);")
        self.b42.setText("")
        self.b42.setAlignment(QtCore.Qt.AlignCenter)
        self.b42.setObjectName("b42")
        self.gridLayout_3.addWidget(self.b42, 10, 1, 1, 1)
        self.b45 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b45.sizePolicy().hasHeightForWidth())
        self.b45.setSizePolicy(sizePolicy)
        self.b45.setMaximumSize(QtCore.QSize(72, 72))
        self.b45.setStyleSheet("background-color:rgb(187, 255, 171);")
        self.b45.setText("")
        self.b45.setAlignment(QtCore.Qt.AlignCenter)
        self.b45.setObjectName("b45")
        self.gridLayout_3.addWidget(self.b45, 10, 5, 1, 1)
        self.b73 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b73.sizePolicy().hasHeightForWidth())
        self.b73.setSizePolicy(sizePolicy)
        self.b73.setMaximumSize(QtCore.QSize(72, 72))
        self.b73.setStyleSheet("background-color: rgb(20, 138, 0);")
        self.b73.setText("")
        self.b73.setAlignment(QtCore.Qt.AlignCenter)
        self.b73.setObjectName("b73")
        self.gridLayout_3.addWidget(self.b73, 13, 2, 1, 1)
        self.b82 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b82.sizePolicy().hasHeightForWidth())
        self.b82.setSizePolicy(sizePolicy)
        self.b82.setMaximumSize(QtCore.QSize(72, 72))
        self.b82.setStyleSheet("background-color: rgb(20, 138, 0);")
        self.b82.setText("")
        self.b82.setAlignment(QtCore.Qt.AlignCenter)
        self.b82.setObjectName("b82")
        self.gridLayout_3.addWidget(self.b82, 14, 1, 1, 1)
        self.b25 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b25.sizePolicy().hasHeightForWidth())
        self.b25.setSizePolicy(sizePolicy)
        self.b25.setMaximumSize(QtCore.QSize(72, 72))
        self.b25.setStyleSheet("background-color:rgb(187, 255, 171);")
        self.b25.setText("")
        self.b25.setAlignment(QtCore.Qt.AlignCenter)
        self.b25.setObjectName("b25")
        self.gridLayout_3.addWidget(self.b25, 8, 5, 1, 1)
        self.b58 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b58.sizePolicy().hasHeightForWidth())
        self.b58.setSizePolicy(sizePolicy)
        self.b58.setMaximumSize(QtCore.QSize(72, 72))
        self.b58.setStyleSheet("background-color:rgb(187, 255, 171);")
        self.b58.setText("")
        self.b58.setAlignment(QtCore.Qt.AlignCenter)
        self.b58.setObjectName("b58")
        self.gridLayout_3.addWidget(self.b58, 11, 12, 1, 1)
        self.b15 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b15.sizePolicy().hasHeightForWidth())
        self.b15.setSizePolicy(sizePolicy)
        self.b15.setMaximumSize(QtCore.QSize(72, 72))
        self.b15.setStyleSheet("background-color: rgb(20, 138, 0);")
        self.b15.setText("")
        self.b15.setAlignment(QtCore.Qt.AlignCenter)
        self.b15.setObjectName("b15")
        self.gridLayout_3.addWidget(self.b15, 7, 5, 1, 1)
        self.b74 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b74.sizePolicy().hasHeightForWidth())
        self.b74.setSizePolicy(sizePolicy)
        self.b74.setMaximumSize(QtCore.QSize(72, 72))
        self.b74.setStyleSheet("background-color:rgb(187, 255, 171);")
        self.b74.setText("")
        self.b74.setAlignment(QtCore.Qt.AlignCenter)
        self.b74.setObjectName("b74")
        self.gridLayout_3.addWidget(self.b74, 13, 3, 1, 1)
        self.b31 = CQLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b31.sizePolicy().hasHeightForWidth())
        self.b31.setSizePolicy(sizePolicy)
        self.b31.setMaximumSize(QtCore.QSize(72, 72))
        self.b31.setStyleSheet("background-color: rgb(20, 138, 0);")
        self.b31.setText("")
        self.b31.setAlignment(QtCore.Qt.AlignCenter)
        self.b31.setObjectName("b31")
        self.gridLayout_3.addWidget(self.b31, 9, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.horizontalFrame = QtWidgets.QFrame(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame.sizePolicy().hasHeightForWidth())
        self.horizontalFrame.setSizePolicy(sizePolicy)
        self.horizontalFrame.setMaximumSize(QtCore.QSize(600, 40))
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.white_timer = QtWidgets.QLabel(self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.white_timer.sizePolicy().hasHeightForWidth())
        self.white_timer.setSizePolicy(sizePolicy)
        self.white_timer.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.white_timer.setFont(font)
        self.white_timer.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.white_timer)
        self.label_7 = QtWidgets.QLabel(self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.label_9 = QtWidgets.QLabel(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.black_timer = QtWidgets.QLabel(self.horizontalFrame)
        self.black_timer.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.black_timer.setFont(font)
        self.black_timer.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.black_timer.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.black_timer)
        self.verticalLayout.addWidget(self.horizontalFrame)
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        
        
        
        oImage = QtGui.QImage("imgs/homepage1.jpg")
        sImage = oImage.scaled(QtCore.QSize(600,900))  
        palette = QtGui.QPalette()
        palette.setBrush(QtGui.QPalette.Window, QtGui.QBrush(sImage))                        
        MainWindow.setPalette(palette)
        

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.play.clicked.connect(lambda : self.setChessPage(MainWindow))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "2PlayerCHESS"))
        self.label.setText(_translate("MainWindow", "white\'s Timer"))
        self.label_2.setText(_translate("MainWindow", "Mins"))
        self.label_3.setText(_translate("MainWindow", "Secs"))
        self.label_4.setText(_translate("MainWindow", "Black\'s Timer"))
        self.label_10.setText(_translate("MainWindow", "Mins"))
        self.label_1.setText(_translate("MainWindow", "Secs"))
        self.label_11.setText(_translate("MainWindow", "2Player CHESS"))
        self.play.setText(_translate("MainWindow", "PLAY"))
        self.label_5.setText(_translate("MainWindow", "White\'s Clock :"))
        self.white_timer.setText(_translate("MainWindow", "00:00"))
        self.label_7.setText(_translate("MainWindow", "White\'s Turn"))
        self.label_9.setText(_translate("MainWindow", "Black\'s Clock : "))
        self.black_timer.setText(_translate("MainWindow", "00:00"))
    
    def setChessPage(self,mainwin):
        self.stackedWidget.setCurrentIndex(1)
        self.white_timer.setText(self.w_mins.text()+':'+self.w_secs.text())
        self.black_timer.setText(self.b_mins.text()+':'+self.b_secs.text())
        self.begin(mainwin)
        
    def begin(self,mainwin):
        cls = Ui_MainWindow
        cls.whites_clock = ClockThread(self.white_timer, self.label_7, "White",mainwin)
        cls.blacks_clock = ClockThread(self.black_timer, self.label_7, "Black",mainwin)
        cls.whites_clock.start()
        cls.blacks_clock.start()
        
        ui_board=[[None for j in range(9)]for i in range(9)]
        for i in range(1,9):
            for j in range(1,9):
                ui_board[i][j]=eval("self.b"+str(i)+str(j))
        # print(ui_board,sep='\n')
        import chess
        global game       
        game = chess.Game(self,ui_board)
        
    @classmethod
    def clockChange(cls,team):
        if team==1:
            cls.blacks_clock.Turn.set()
            cls.whites_clock.Turn.clear()
        else:
            cls.whites_clock.Turn.set()
            cls.blacks_clock.Turn.clear() 
        


class CQLabel(QtWidgets.QLabel):
    trigger = QtCore.pyqtSignal()
    clockChanged = QtCore.pyqtSignal(int)
    selected = None
    color = ''

    def __init__(self,parent):
        super().__init__(parent)
        self.trigger.connect(self.highlight)
        self.clockChanged.connect(Ui_MainWindow.clockChange)
        
    def mousePressEvent(self,event):
        self.trigger.emit()
        if game.captureClicks(self.objectName(), game.team):
            if game.team==1:
                Ui_MainWindow.clockChange(1)
                # game.flipBoard(self.objectName())
                game.team=2
            else:
                Ui_MainWindow.clockChange(2)
                # game.flipBoard(self.objectName())
                game.team=1
        
    def highlight(self):
        prev_color = self.styleSheet()
        self.setStyleSheet("""background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5,
                           radius:0.42, fx:0.5, fy:0.5, stop:0.852273 rgba(176, 255, 0, 255),
                           stop:1 rgba(255, 255, 255, 255));""")
        selected,color = CQLabel.selected,CQLabel.color
        if self != selected:
            CQLabel.color=prev_color
            CQLabel.selected=self
            if selected!=None:
                selected.setStyleSheet(color)



class ClockThread(threading.Thread):
    
    def __init__(self,label,status_label,player,mainwin):
        super().__init__()
        self.mainwin = mainwin
        self.label = label
        self.status_label = status_label
        self.player = player
        self.clock = self.label.text().split(':')
        self.Turn = threading.Event()
    
    def run(self):
        secs = int(self.clock[1])
        mins = int(self.clock[0])
        self.Turn.wait()
        while (mins+secs) != 0:
            if not self.Turn.is_set():
                self.Turn.wait()
            if secs == 0:
                mins -= 1
                secs = 59
            else:
                secs -= 1
            self.label.setText(str(mins)+':'+str(secs))
            self.status_label.setText(self.player+"'s Turn")
            time.sleep(1)
        self.onTimeout(self.player)
            
    def onTimeout(self, player):
        if self.player == "White":
            self.status_label.setText("Black WON!")
        if self.player == "Black":
            self.status_label.setText("White WON!")
        time.sleep(2.5)
        self.mainwin.close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
